[package]
name = "joel"
version = "0.1.0"
authors = ["Fabian Eriksson <fabian.eriksson@r2m.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.10.9", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
rocket = "0.4.6"
rocket_contrib = { version = "0.4.6", default-features = false, features = ["json"] }
chrono = "0.4.19"