[package]
name = "joel-bot"
version = "1.0.2"
authors = [
    "Fabian Eriksson <fabian.eriksson@r2m.se>",
    "Joakim Anell <an3ll@hotmail.com>",
    "Simon Olander <supersimon@spray.se>",
]
edition = "2018"

[lib]
name = "slack"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.4"
rocket = { version = "0.4.11" }
rocket_contrib = { version = "0.4.11", default-features = false, features = ["json"] }
chrono = "0.4.22"
clokwerk = "0.3.5"
rand = "0.8.5"
