intro:
  greetings:
    - "Hej hörni! :joel:"
    - "Tjenis! Är allt väl? :joel:"
    - "Yo, allt väl hoppas jag? :joel:"
  about_me: "Mitt namn är joel-bot och jag har axlat @chikken's arbete nu när han inte längre finns ibland oss!\nJag kommer pliktskyldigt påminna er om att tidsrapportera sista arbetsdagen i månaden och kan även svara på frågor kring tidrapportering.\nNi kan läsa mig här: https://github.com/r2m/joel-bot"
  features:
    - "tid - fråga mig om när ni ska tidsrapportera denna månaden"
    - "pricing - hur mycket kostar jag, alltså vad skulle det kosta att köra en on-premise joel-bot?"
    - "skribenter - mina skapare, _i bokstavsordning på efternamn_"
  credits:
    intro: "Ni kan skylla på dessa skinn om jag inte funkar!"
    names:
      - "Joakim Anell (@an3ll)"
      - "Fabian Eriksson (@fabulicious)"
      - "Simon Olander (@simon)"

time_report:
  beginning:
    general:
      - "hejsan allihopa det är jag som är joel bot"
    1:
      - "nytt år, nya friska tag!"
    3:
      - "påskharen kommer ta er alla"
    12:
      - "Julen är på gång, ho ho ho"

  middle:
    general:
      - "tidrapportera för fan (っ◔◡◔)っ"
      - "nu är det nog ta mig fasen dags att tidrapportera"
    1:
      - "pulkan är pajj, köp ny"

  end:
    general:
      - "tack och hej, era losers ¯\\_(ツ)_/¯"
      - "det var allt för mig, hej då allihopa, önskar joel-bot"
    12:
      - "tomten är full, och jag med, så nu drar jag"
