intro:
  greetings:
    - "Hej hörni! :joel:"
    - "Tjenis! Är allt väl? :joel:"
    - "Yo, allt väl hoppas jag? :joel:"
  about_me: "Mitt namn är joel-bot och jag har axlat @chikken's arbete nu när han inte längre finns ibland oss!\nJag kommer pliktskyldigt påminna er om att tidsrapportera sista arbetsdagen i månaden och kan även svara på frågor kring tidrapportering.\nNi kan läsa mig här: https://github.com/Pirayya/joel-bot"
  features:
    - "tid - fråga mig om när ni ska tidsrapportera denna månaden"
    - "pricing - hur mycket kostar jag, alltså vad skulle det kosta att köra en on-premise joel-bot?"
    - "skribenter - mina skapare, _i bokstavsordning på efternamn_"
  credits:
    intro: "Ni kan skylla på dessa skinn om jag inte funkar!"
    names:
      - "Joakim Anell (@an3ll)"
      - "Fabian Eriksson (@fabulicious)"
      - "Simon Olander (@simon)"

time_report:
  beginning:
    general:
      - "Hejsan allihopa, som den halvdassigt skrivna bot jag är, har jag som uppdrag att påminna er om följande:"
      - "Min elektroniska klocka har slagit, och det är dags att förmedla mitt budskap."
      - "Tjenixen hoppas det är bra med alla!"
      - "Hej alla kära medarbetare, hoppas ni som vanligt jobbar på lite enklare och mycket smartare."
    1:
      - "Ring in det nya och ring ut det gamla i årets första, skälvande månad."
    3:
      - "A men tjenare! Denna månad har jag ett meddelande från självaste påskharen:"
    12:
      - "Nu tindrar stjärnor i det blå i hus och fönster likaså och alla röda tomtar gå med vita skägg och luvor på."

  middle:
    general:
      - "Det är sista arbetsdagen i månaden och det är dags att tidrapportera (っ◔◡◔)っ"
      - "Nu är det sista dagen att tidrapportera för denna månad."
      - "Ännu en månad börjar röra sig mot sitt slut, och i och med det är det dags att tidrapportera."
    1:
      - "En sak som dock inte är nytt, är att det är slutet på månaden och det är dags att tidrapportera."
    12:
      - "Från djupet av min cpu till er alla: Kom ihåg att tidrapportera!"

  end:
    general:
      - "Tack och hej! ¯\\_(ツ)_/¯"
      - "Det var allt för mig, hej då allihopa!"
      - "Over and out!"
    12:
      - "Gott Nytt År! Önskar joel-bot"
