name: Rust CI/CD

on:
  release:
    types: [ published ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get version from github ref
      id: get_version
      run: echo "{VERSION}={${GITHUB_REF/refs\/tags\//}}" >> $GITHUB_OUTPUT


    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: r2mhub/joel-bot:${{ steps.get_version.outputs.VERSION }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build_and_push

    steps:
    - name: Get version from github ref
      id: get_version
      run: echo "{VERSION}={${GITHUB_REF/refs\/tags\//}}" >> $GITHUB_OUTPUT

    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy joel-bot
      uses: azure/webapps-deploy@v2
      with:
        app-name: joel-bot
        images: r2mhub/joel-bot:${{ steps.get_version.outputs.VERSION }}

    - name: Azure logout
      run: |
        az logout
